app.path=apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
appium.url=http://127.0.0.1:4723

platformName=Android
platformVersion=16
deviceName=Android
automationName=UiAutomator2

appPackage=com.swaglabsmobileapp
appActivity=com.swaglabsmobileapp.MainActivity

noReset=true